### ISSUE TITLE
GetCredentialsAsync - It shouldn't matter if auth key starts with or without scheme

### ISSUE THREAD

**Issue by hilmer-martin** [mthalman/docker-creds-provider#18]
### Problem description:

CredsProvider does not find Auth-Entry in docker config file if it starts with scheme like https:// but the given registry name does not contain a scheme.

### Backround:
This library is used for .NET containers feature on which we rely for building our container images.
In Azure DevOps we use a password based service connection for authentication to our container registry. The docker registry url must contain scheme otherwise you get an validation error "invalid url". To get the credentials stored in docker config we use the docker task which saves this url including scheme to docker config in auths section.

To get this solved we tried to set the container registry path in csproj with scheme. Then we get an validation error like "invalid registry name".

### Proposed solution:
After some code inspection I found this line https://github.com/mthalman/docker-creds-provider/blob/5701f6667c1fbd805684857baaa860383bbdfed7/src/Valleysoft.DockerCredsProvider/CredsProvider.cs#L101 which only looks for equivalent auth keys.

It would be nice if we can extend the logic that it doesn't matter if the registry auth key has scheme or not.
I found the implementation in docker-cli which does strip the scheme from the registry auth key.
https://github.com/docker/cli/blob/master/cli/config/credentials/file_store.go#L39

I suggest to strip scheme from input value and from config, when looking for an entry.

Thank you for sharing this library. 
I'm happy to suggest the changes with a PR. Please give me short feedback if you agree with the suggested change.

**Comment by mthalman** [comment]
@hilmer-martin - Thanks for the thorough analysis. Yes, please do submit a PR with your suggested changes. Please also include a test that verifies the new logic.

**Comment by baronfel** [comment]
Thanks for the ping - am I understanding correctly that the SDK Containers feature should update this library and that's all the action required?

@hilmer-martin is this blocking you from migrating to 8.0.100? I can definitely get this into February's 8.0.200, but would have to get approval for 8.0.100 servicing fixes.

**Comment by hilmer-martin** [comment]
@baronfel we implemented a workaround because this is blocking us from pushing new images. We can live with that till this is fixed - so plan integration when ever you want.

Thank you for your fast responds.

**Comment by mthalman** [comment]
> Thanks for the ping - am I understanding correctly that the SDK Containers feature should update this library and that's all the action required?

@baronfel - Yep. I would recommend taking this fix in 8.0.200. I've created a release for it: https://github.com/mthalman/docker-creds-provider/releases/tag/v2.2.1.

**Comment by baronfel** [comment]
Thanks @mthalman - I'll get that ported over to the internal feeds and get it updated in the SDK for 8.0.200.
